uploads = []
generated = []

[[outputs]]
id = "QTcPwAQQX-sRNfCk_J5oK"
uri = "file://README.md"
type = "text"
title = "README.md"

[[outputs]]
id = "rmh5qC6effnkWYw4_-C0x"
uri = "file://docs/product-overview.md"
type = "text"
title = "Product Overview"

[[outputs]]
id = "JkoWnQGwRaLpS8LyRWBYR"
uri = "file://docs/technical-architecture.md"
type = "text"
title = "Technical Architecture"
